server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload:
    type: OSS
    path-prefix: "uat"

oss:
  enable: true
  endpoint: hhh
  keyId: xxx
  keySecret: yyy
  bucket: zzz
